name: C/C++ CI

on:
  push:
    branches: [ "main*", "development" ]
  pull_request:
    branches: [ "main*", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: make
      run: make
      
    - name: list generated files
      run: |
          ls -alth
