name: C/C++ CI

on:
  push:
    branches: [ "main", "development", "experimental", "test*" ]
  pull_request:
    branches: [ "main", "development", "experimental", "test*" ]

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:        
        runs-on: [ubuntu-latest, macos-latest ]
        python-version: [ 3.9, "3.11" ]

    steps:
    - uses: actions/checkout@v4

    - name: C++ info
      run: g++ -v

    - name: Run C++ tests 
      run: |
          make tests
          ./tests

    - name: Test makefile
      run: make

    - name: Test directly running main program
      run: |
        ./main -p 6  # Note: small population of 6 for quick runtime
        ls -alth

    - name: Test Python command line script
      run: |
        pip install numpy matplotlib
        python run_main.py -R 1233 -p 6 --doEvol --folderName exampleRun2  # Note: small population of 6 for quick runtime

    - name: Test using OMV 1
      run: |
        pip install OSBModelValidation
        omv all -V 
        git diff exampleRun/phenotype.dat 

    - name: Test using OMV 2
      run: |
        # Running OMV multiple times to test whether run results are nondeterministic
        omv all -V 
        git diff exampleRun/phenotype.dat 

    - name: Test using OMV 3
      run: |
        # Running OMV multiple times to test whether run results are nondeterministic
        omv all -V 
        git diff exampleRun/phenotype.dat 
      
    - name: list generated files
      run: |
          ls -alth
