name: C/C++ CI

on:
  push:
    branches: [ "main", "development", "experimental", "test*" ]
  pull_request:
    branches: [ "main", "development", "experimental", "test*" ]

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:        
        runs-on: [ubuntu-latest, macos-latest ]
        python-version: [ 3.9, "3.11" ]

    steps:
    - uses: actions/checkout@v4

    - name: C++ info
      run: g++ -v

    - name: Install dependencies (Ubuntu)
      run: sudo apt-get install -y nlohmann-json3-dev
      if: matrix.runs-on == 'ubuntu-latest'
      
    - name: Install dependencies (macOS)
      run: brew install nlohmann-json
      if: ${{ contains(matrix.runs-on, 'macos') }}
    
    - name: Run C++ tests 
      run: |
          make tests
          ./tests

    - name: Test makefile
      run: make

    - name: Test directly running main program
      run: |
        ./main -p 6  # Note: small population of 6 for quick runtime
        ls -alth

    - name: Test Python command line script
      run: |
        pip install numpy matplotlib
        python run_main.py -R 1233 -p 6 --doEvol --folderName exampleRun2  # Note: small population of 6 for quick runtime

    - name: Test using test_all.sh
      run: |
        pip install neuron
        which neuron
        export NEURON_HOME=$pythonLocation
        env
        pip install OSBModelValidation
        
        ./test_all.sh 

        git diff exampleRun/phenotype.dat 

    - name: Test NeuroML
      run: |
        pip install pyNeuroML
        cd neuroml
        ./regenerate.sh 

    - name: Test C++/Python interactions
      run: |
        cd test_files
        ./test.sh 

      
    - name: list generated files
      run: |
          ls -alth
