name: C/C++ CI

on:
  push:
    branches: [ "main*", "development" ]
  pull_request:
    branches: [ "main*", "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: make and run test
      run: |
         pip install matplotlib
         ./test_all.sh 
         git diff

      
    - name: list generated files
      run: |
          ls -alth
