name: C/C++ CI

on:
  push:
    branches: [ "main", "development", "experimental", "test*" ]
  pull_request:
    branches: [ "main", "development", "experimental", "test*" ]

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:        
        runs-on: [ubuntu-latest, macos-latest ]
        python-version: [ 3.9, "3.11" ]

    steps:
    - uses: actions/checkout@v4

    - name: make
      run: make
      
    - name: list generated files
      run: |
          ls -alth
