name: C/C++ CI

on:
  push:
    branches: [ "main", "development", "experimental", "test*" ]
  pull_request:
    branches: [ "main", "development", "experimental", "test*" ]

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:        
        runs-on: [ubuntu-latest, macos-latest ]
        python-version: [ 3.9, "3.11" ]

    steps:
    - uses: actions/checkout@v4

    - name: C++ info
      run: g++ -v

    - name: Test makefile
      run: make

    - name: Test directly running main program
      run: |
        ./main
        ls -alth

    - name: Test Python command line script
      run: |
        pip install numpy matplotlib
        python run_main.py -R 1234 -p 96 --doEvol --folderName exampleRun2

    - name: Test Python script access
      run: |
        python test.py

    - name: Test using OMV
      run: |
        pip install OSBModelValidation
        omv all -V 
      
    - name: list generated files
      run: |
          ls -alth
